# Generated by Django 5.0.1 on 2024-01-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [   
        ('app_anime_list', '0002_alter_anime_episodes_alter_anime_my_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anime_list.animetype'),
        ),
    ]
